### PR TITLE
Added IProxy and fixed errors

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Zaggy1024** [comment]
Hmm, not sure the drops utilities should be in here, they're not quite relevant to the combos.

**Comment by Zaggy1024** [comment]
Same with ClientFunction and ServerFunction, plus they have to be implemented by at least anonymous classes to be able to use @SideOnly to avoid class loading errors.

**Comment by ghost** [comment]
How would we do these without ClientFunction?
- https://github.com/MrIbby/minecraft-combos/blob/77b620a/src/main/java/zaggy1024/combo/VariantsOfTypesCombo.java#L461-L501
- https://github.com/MrIbby/minecraft-combos/blob/77b620a/src/main/java/zaggy1024/combo/VariantsOfTypesCombo.java#L508-L527

**Comment by Zaggy1024** [comment]
Both could probably be moved to SideOnly functions in VariantsOfTypesCombo, perhaps even combined into one function.

**Comment by ghost** [comment]
Like this? `if (FMLCommonHandler.getInstance().getSide().isClient) registerResourceLocations();`

**Comment by Zaggy1024** [comment]
Hmm, hadn't thought about how to make it determine the side.. that seems pretty inefficient, though, perhaps the proxy should have a getSide..

**Comment by ghost** [comment]
🎉

**Pull request merged**
